# Generated by Django 3.1.2 on 2020-10-17 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Belt_group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('belt_color', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Techniques',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('img_url', models.CharField(max_length=200)),
                ('belt_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.belt_group')),
            ],
        ),
    ]
