# Generated by Django 3.1.2 on 2020-10-18 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_techniques_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techniques',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
