# Generated by Django 3.1.2 on 2020-11-02 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20201018_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='techniques',
            name='img_url',
        ),
    ]
